version: '3.4'

services:
  turnipteams.web:
    image: ${DOCKER_REGISTRY-}turnipteamsweb
    build:
      context: .
      dockerfile: TurnipTeams/Dockerfile
      args:
        - skip_client_build=true
  turnipteams.web.angular.app:
    image: ${DOCKER_REGISTRY-}turnipteamsangularapp
    build:
      context: .
      dockerfile: TurnipTeams/ClientApp/Dockerfile
    ports:
      - "4200:4200" 
      - "49153:49153"
    volumes:
      - ./TurnipTeams/ClientApp:/app